name: Scrape Jumia Products

on:
  schedule:
    - cron: '0 8 * * *'  # 
  workflow_dispatch:     # 

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27018:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Debug repo files
        run: ls -R

      - name: Run scraper
        env:
          MONGO_URI: "mongodb://localhost:27018"
        run: python scraper.py
