name: Scrape Jumia Products

on:
  schedule:
    - cron: '0 8 * * *'  # كل يوم مع 8h UTC
  workflow_dispatch:     # باش تقدر تشغلو يدوي

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27018:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show repo files (debug)
        run: ls -R

      - name: Run app
        env:
          MONGO_URI: mongodb://localhost:27018
        run: python app.py
