name: Scrape Jumia Products

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h UTC
  workflow_dispatch:     # Permet de lancer manuellement

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27018:27017  # port externe:interne
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        env:
          MONGO_URI: "mongodb://localhost:27018"
        run: python scraper.py
